name: navo-workshop
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.16.*
  - astropy=3.2.*
  - matplotlib
  - requests
  - jupyterlab=1.2.*
  - scipy
  - aplpy
  - pip
  - pip:
    - git+git://github.com/astropy/astroquery.git
    - git+git://github.com/astropy/pyvo.git
    - git+git://github.com/NASA-NAVO/navo.git
